### ISSUE TITLE
Versão do react

### ISSUE THREAD

**Issue by Andreeyzin** [liliassz/ProjetoFinal_OneBitCode#6]
O front está ok porém está dando alguns erros nas dependência do react 18, recomendo vc usar a versão 16 está mais estável para esse tipo de projeto

**Comment by liliassz** [comment]
Se você insta as dependências usando o instalador de pacotes **Yarn** não dá erro porém no **NPM I** notei alguns erros de compatibilidade no console, na próxima atualização irei mudar a versão do react
